# Generated by Django 2.0.4 on 2018-05-07 20:26

from django.db import migrations
import xml.etree.ElementTree as ET
import os



# python with DictReader, which takes the first line/header as keys
def import_data(apps, schema_editor):
    datadir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'data','tanzil'))
    data = ET.parse(os.path.join(datadir,'quran-simple-enhanced.xml')).getroot()
    
    Sura = apps.get_model('qurandata', 'Sura')
    Aya = apps.get_model('qurandata', 'Aya')
    
    Sura.objects.all().delete()
    
    for suradata in data.findall('sura'):
        s = suradata.attrib
        ayas = suradata.findall('aya')
        sura = Sura.objects.create(
            index=int(s['index']),
            ayas=len(ayas),
            name=s['name'])
        ayaslist = []
        for ayadata in ayas:
            a = ayadata.attrib
            ayaslist.append(
                Aya(sura=sura, index=int(a['index']),
                    text=a['text'])
            )
        Aya.objects.bulk_create(ayaslist)
            
def clear_data(apps, schema_editor):
    Sura = apps.get_model('qurandata', 'Sura')
    Sura.objects.all().delete()
            
class Migration(migrations.Migration):

    dependencies = [
        ('qurandata', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_data, clear_data),
    ]
