# Generated by Django 2.0.4 on 2018-10-04 18:38

from django.db import migrations
from django.db import migrations
import xml.etree.ElementTree as ET
import os



def import_data(apps, schema_editor):
    datadir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'data','tanzil'))
    data = ET.parse(os.path.join(datadir,'quran-data.xml')).getroot()

    Aya = apps.get_model('qurandata', 'Aya')
    Sura = apps.get_model('qurandata', 'Sura')
    Quarter = apps.get_model('qurandata', 'Quarter')
    
    def _prevaya(si,ai):
        if ai>1: return (si,ai-1)
        s = Sura.objects.get(index=si-1)
        return (si-1,s.ayas)
    
    Quarter.objects.all().delete()
    qlist=[]
    
    for qrdata in data.findall('hizbs/quarter'):
        qd=qrdata.attrib
        i=int(qd['index'])
        si=int(qd['sura'])
        ai=int(qd['aya'])
        q = Quarter(index=i,
            hizb=((i-1)//4)+1, 
            pos_in_hizb=((i-1)%4)+1,
            startaya=Aya.objects.get(sura__index=si, index=ai))
        if len(qlist) > 0:
            psi,pai=_prevaya(si,ai)
            qlist[-1].endaya = Aya.objects.get(sura__index=psi, index=pai)
            
        qlist.append(q)
    lastsura=Sura.objects.order_by('-index').first()
    qlist[-1].endaya = Aya.objects.get(sura=lastsura, index=lastsura.ayas)
    Quarter.objects.bulk_create(qlist)
            
def clear_data(apps, schema_editor):
    Quarter = apps.get_model('qurandata', 'Quarter')
    Quarter.objects.all().delete()
    


class Migration(migrations.Migration):

    dependencies = [
        ('qurandata', '0003_quarter'),
    ]

    operations = [
        migrations.RunPython(import_data, clear_data),
    ]
