# Generated by Django 2.0.4 on 2020-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurandata', '0004_auto_20181004_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='aya',
            name='page',
            field=models.PositiveIntegerField(default=0, verbose_name='Page in madani quran'),
            preserve_default=False,
        ),
    ]
