# Generated by Django 2.0.4 on 2020-03-07 10:48

from django.db import migrations
from django.db.models import Q
import xml.etree.ElementTree as ET
import os



def import_data(apps, schema_editor):
    datadir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'data','tanzil'))
    data = ET.parse(os.path.join(datadir,'quran-data.xml')).getroot()

    Aya = apps.get_model('qurandata', 'Aya')
    
    def _prevaya(si,ai):
        if ai>1: return (si,ai-1)
        s = Sura.objects.get(index=si-1)
        return (si-1,s.ayas)
    # contains (page, start_sura, start_aya)
    ranges = []
    
    for elem in data.findall('pages/page'):
        qd=elem.attrib
        ranges.append((int(qd['index']),int(qd['sura']),int(qd['aya'])))
   
    ranges.sort() #Additional security (norammlly already sorted)
    
    
    for i in range(0,len(ranges)-1):
        p,s,a = ranges[i]
        _,ns,na = ranges[i+1]
        # Ayas of start of page surah
        if ns == s:
            # All page in same sura
            Aya.objects.filter(sura__index=s, index__gte=a, index__lt=na)\
                .update(page=p)
            continue
        
        Aya.objects.filter(
            Q(sura__index=s, index__gte=a) # Ayas of starting sura until end
            | Q(sura__index__gt=s, sura__index__lt=ns) # Ayas included in page.
            | Q(sura__index=ns, index__lt=na) #Ayas before next page start of na 
            ).update(page=p)
        
    
    p, s, a = ranges[-1]
    Aya.objects.filter(
        Q(sura__index=s, index__gte=a) # Ayas of starting sura until end
        | Q(sura__index__gt=s) # and remaining ayas
        ).update(page=p)
            


class Migration(migrations.Migration):

    dependencies = [
        ('qurandata', '0005_aya_page'),
    ]

    operations = [
        migrations.RunPython(import_data),
    ]
